runmode: debug
addr: :9999
name: apiserver
url: http://127.0.0.1:9999
max_ping_count: 10
jwt_secret: Rtg8BPKNEf2mB4mgvKONGPZZQSaJWNLijxR42qRgq0iBb5
log:
  writers: file,stdout
  logger_level: DEBUG
  logger_file: log/apiserver.log
  log_format_text: false
  rollingPolicy: size
  log_rotate_date: 1
  log_rotate_size: 1
  log_backup_count: 7
gormlog: true
db:
  name: db_apiserver
  addr: 127.0.0.1:3306
  username: root
  password: password
docker_db:
  name: db_apiserver
  addr: 127.0.0.1:3306
  username: root
  password: password
tls:
  addr: :9090
  cert: conf/server.crt
  key: conf/server.key